apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Maven
        uses: docker://maven:3.9.3-eclipse-temurin-17-alpine
        shell: sh
        run: |
          mvn clean install
